#!/bin/bash

PROJECT_PATH=$(dirname $(readlink -f $0))

cd $PROJECT_PATH

./covid19cases.rb > covid19cases.txt && git add . && git commit -m "Update result" && git push

./covid19cases.rb > /srv/public/covid19cases.txt && ./covid19cases.rb html > /srv/public/covid19cases.html
